<a href="https://colab.research.google.com/github/W-B28/DS-Unit-1-Sprint-1-Data-Wrangling-and-Storytelling/blob/master/William_Bell_Assignment_LS_DS_112_Make_Features.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>

# Assignment:

- Replicate the lesson code.

 - This means that if you haven't followed along already, type out the things that we did in class. Forcing your fingers to hit each key will help you internalize the syntax of what we're doing. Make sure you understand each line of code that you're writing, google things that you don't fully understand.
 - [Lambda Learning Method for DS - By Ryan Herr](https://docs.google.com/document/d/1ubOw9B3Hfip27hF2ZFnW3a3z9xAgrUDRReOEo-FHCVs/edit?usp=sharing)
- Convert the `term` column from string to integer.
- Make a column named `loan_status_is_great`. It should contain the integer 1 if `loan_status` is "Current" or "Fully Paid." Else it should contain the integer 0.
- Make `last_pymnt_d_month` and `last_pymnt_d_year` columns.

In [0]:
##### Begin Working Here #####
import pandas as pd

In [0]:
df = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/Ames%20Housing%20Data/train.csv')

df.head()

In [0]:
# display options

pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 200)

df.dtypes

In [0]:
# Look at the first ten rows of the `BedroomAbvGr` column.

df['BedroomAbvGr'].head()

In [0]:
df['LotFrontage'].head(10)

In [0]:
# counts of possible values in LotFrontage Column

df['LotFrontage'].value_counts(dropna=False)

In [0]:
import numpy as np

type(np.NaN)

### Making New Features

In [0]:
small_df = df[['TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'SalePrice']]

small_df

In [0]:
# Create a new column

small_df['TotalSquareFootage'] = small_df['TotalBsmtSF'] + small_df['1stFlrSF'] + small_df['2ndFlrSF'] 

small_df

## Load new dataset

In [0]:
!wget https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip

LoanStats_2018Q4.cs     [                 <=>]  21.72M   814KB/s    in 28s

2020-01-15 16:14:53 (796 KB/s) - ‘LoanStats_2018Q4.csv.zip.1’ saved [22776791]

In [0]:
!unzip LoanStats_2018Q4.csv.zip

Archive:  LoanStats_2018Q4.csv.zip
replace LoanStats_2018Q4.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n

In [0]:
!head LoanStats_2018Q4.csv

Notes offered by Prospectus (https://www.lendingclub.com/info/prospectus.action)
"id","member_id","loan_amnt","funded_amnt","funded_amnt_inv","term","int_rate","installment","grade","sub_grade","emp_title","emp_length","home_ownership","annual_inc","verification_status","issue_d","loan_status","pymnt_plan","url","desc","purpose","title","zip_code","addr_state","dti","delinq_2yrs","earliest_cr_line","inq_last_6mths","mths_since_last_delinq","mths_since_last_record","open_acc","pub_rec","revol_bal","revol_util","total_acc","initial_list_status","out_prncp","out_prncp_inv","total_pymnt","total_pymnt_inv","total_rec_prncp","total_rec_int","total_rec_late_fee","recoveries","collection_recovery_fee","last_pymnt_d","last_pymnt_amnt","next_pymnt_d","last_credit_pull_d","collections_12_mths_ex_med","mths_since_last_major_derog","policy_code","application_type","annual_inc_joint","dti_joint","verification_status_joint","acc_now_delinq","tot_coll_amt","tot_cur_bal","open_acc_6m","open_act_il","open_il_12m","open_il_24m","mths_since_rcnt_il","total_bal_il","il_util","open_rv_12m","open_rv_24m","max_bal_bc","all_util","total_rev_hi_lim","inq_fi","total_cu_tl","inq_last_12m","acc_open_past_24mths","avg_cur_bal","bc_open_to_buy","bc_util","chargeoff_within_12_mths","delinq_amnt","mo_sin_old_il_acct","mo_sin_old_rev_tl_op","mo_sin_rcnt_rev_tl_op","mo_sin_rcnt_tl","mort_acc","mths_since_recent_bc","mths_since_recent_bc_dlq","mths_since_recent_inq","mths_since_recent_revol_delinq","num_accts_ever_120_pd","num_actv_bc_tl","num_actv_rev_tl","num_bc_sats","num_bc_tl","num_il_tl","num_op_rev_tl","num_rev_accts","num_rev_tl_bal_gt_0","num_sats","num_tl_120dpd_2m","num_tl_30dpd","num_tl_90g_dpd_24m","num_tl_op_past_12m","pct_tl_nvr_dlq","percent_bc_gt_75","pub_rec_bankruptcies","tax_liens","tot_hi_cred_lim","total_bal_ex_mort","total_bc_limit","total_il_high_credit_limit","revol_bal_joint","sec_app_earliest_cr_line","sec_app_inq_last_6mths","sec_app_mort_acc","sec_app_open_acc","sec_app_revol_util","sec_app_open_act_il","sec_app_num_rev_accts","sec_app_chargeoff_within_12_mths","sec_app_collections_12_mths_ex_med","sec_app_mths_since_last_major_derog","hardship_flag","hardship_type","hardship_reason","hardship_status","deferral_term","hardship_amount","hardship_start_date","hardship_end_date","payment_plan_start_date","hardship_length","hardship_dpd","hardship_loan_status","orig_projected_additional_accrued_interest","hardship_payoff_balance_amount","hardship_last_payment_amount","debt_settlement_flag","debt_settlement_flag_date","settlement_status","settlement_date","settlement_amount","settlement_percentage","settlement_term"
"","","6000","6000","6000"," 36 months"," 14.47%","206.44","C","C2","Manager","10+ years","RENT","55000","Verified","Dec-2018","Charged Off","n","","","credit_card","Credit card refinancing","104xx","NY","10.65","0","Jun-2006","0","","","6","0","4196","91.2%","8","w","0.00","0.00","1106.52","1106.52","546.14","272.38","0.0","288.0","51.84","Apr-2019","206.44","","Nov-2019","0","","1","Individual","","","","0","0","12514","0","2","1","1","9","8318","74","1","1","2807","79","4600","1","0","2","2","2086","344","92","0","0","33","150","9","9","0","9","","9","","0","3","4","3","3","3","4","5","4","6","0","0","0","2","100","100","0","0","15800","12514","4300","11200","","","","","","","","","","","","N","","","","","","","","","","","","","","","Y","Oct-2019","ACTIVE","Oct-2019","3479","60.01","24"
"","","24000","24000","24000"," 36 months"," 10.33%","778.14","B","B1","Maintenance Manager","10+ years","MORTGAGE","100000","Not Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","606xx","IL","19.14","0","Oct-1996","3","39","","14","0","8547","27.7%","28","w","16807.30","16807.30","9317.02","9317.02","7192.70","2124.32","0.0","0.0","0.0","Dec-2019","778.14","Jan-2020","Nov-2019","0","57","1","Individual","","","","0","0","273876","3","5","3","5","5","40384","66","2","4","4368","51","30900","8","0","8","9","19563","17353","33","0","0","266","178","4","4","3","4","39","1","39","1","5","5","6","8","15","7","9","5","14","0","0","0","5","82.1","16.7","0","0","335121","50686","25900","61514","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","30000","30000","30000"," 36 months"," 15.02%","1040.26","C","C3","Firefighter ","10+ years","RENT","90000","Verified","Dec-2018","Fully Paid","n","","","debt_consolidation","Debt consolidation","681xx","NE","22.23","0","May-2007","1","","","8","0","25754","48%","23","w","0.00","0.00","30883.673711683","30883.67","30000.00","883.67","0.0","0.0","0.0","Feb-2019","28382.51","","Nov-2019","0","","1","Individual","","","","0","0","51370","1","2","1","2","9","25616","71","2","3","9621","57","53600","0","2","1","5","6421","22030","47","0","0","123","139","3","3","3","3","","3","","0","4","6","4","5","11","6","9","6","8","0","0","0","3","100","50","0","0","89849","51370","41600","36249","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","8000","8000","8000"," 36 months"," 12.98%","269.48","B","B5","Controller","4 years","MORTGAGE","95000","Source Verified","Dec-2018","Current","n","","","credit_card","Credit card refinancing","480xx","MI","9.44","0","Mar-2009","2","73","","7","0","11434","33.3%","20","w","1707.34","1707.34","6855.63","6855.63","6292.66","562.97","0.0","0.0","0.0","Dec-2019","269.48","Jan-2020","Dec-2019","0","73","1","Individual","","","","0","0","247933","5","1","3","4","2","13716","98","4","5","8918","52","34300","2","0","7","10","35419","22866","33.3","0","0","13","117","6","2","1","6","73","2","73","1","3","3","5","15","4","5","15","3","7","0","0","0","8","100","20","0","0","271550","25150","34300","14000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","22400","22400","22400"," 60 months"," 16.14%","546.4","C","C4","Paramedic/ Fire Fighter","10+ years","OWN","56000","Source Verified","Dec-2018","Current","n","","","credit_card","Credit card refinancing","234xx","VA","18.47","0","Dec-2004","0","75","","15","0","13555","38.2%","22","w","19230.91","19230.91","6526.67","6526.67","3169.09","3357.58","0.0","0.0","0.0","Dec-2019","546.4","Jan-2020","Nov-2019","0","","1","Individual","","","","0","0","217072","0","3","1","1","7","18515","79","1","1","5789","55","35500","1","0","4","2","14471","15054","46.6","0","0","113","168","7","7","5","36","","5","","0","5","7","8","8","5","11","12","7","15","0","0","0","2","95.5","25","0","0","253539","32070","28200","23364","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","5000","5000","5000"," 36 months"," 12.98%","168.43","B","B5","Consultant","2 years","RENT","80000","Not Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","100xx","NY","2.39","0","Jan-2014","1","","","8","0","7356","9.4%","9","w","3543.19","3543.19","2015.75","2015.75","1456.81","558.94","0.0","0.0","0.0","Dec-2019","168.43","Jan-2020","Nov-2019","0","","1","Individual","","","","0","0","7356","0","0","0","0","","0","","2","2","4957","9","78200","1","0","1","2","920","70844","9.4","0","0","","59","11","11","0","11","","1","","0","4","4","8","8","0","8","8","4","8","0","0","0","2","100","12.5","0","0","78200","7356","78200","0","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","27000","27000","27000"," 60 months"," 15.02%","642.62","C","C3","Supervisor ","10+ years","MORTGAGE","45000","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","656xx","MO","23.55","2","Oct-2006","0","12","","11","0","12903","64.8%","24","w","23082.62","23082.62","7677.64","7677.64","3917.38","3760.26","0.0","0.0","0.0","Dec-2019","642.62","Jan-2020","Dec-2019","0","","1","Individual","","","","0","0","21902","0","1","0","0","42","8999","42","0","1","5787","53","19900","0","1","0","1","1991","3225","78.1","0","0","144","146","17","17","1","17","33","","12","0","6","8","7","13","5","10","18","8","11","0","0","0","0","87.5","57.1","0","0","41500","21902","14700","21600","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","10000"," 36 months"," 16.14%","352.27","C","C4","","< 1 year","MORTGAGE","90000","Not Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","934xx","CA","7.85","0","Jun-2009","0","","","10","0","17271","48.5%","12","w","7184.51","7184.51","4213.79","4213.79","2815.49","1398.30","0.0","0.0","0.0","Dec-2019","352.27","Jan-2020","Nov-2019","0","","1","Individual","","","","0","0","24085","1","1","0","1","15","6814","68","2","5","11822","53","35600","1","0","0","6","2409","10982","59.3","0","0","114","56","1","1","0","1","","15","","0","3","4","8","8","2","9","10","4","10","0","0","0","2","100","37.5","0","0","45600","24085","27000","10000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""

In [0]:
!tail LoanStats_2018Q4.csv

"","","5600","5600","5600"," 36 months"," 13.56%","190.21","C","C1","","n/a","RENT","15600","Not Verified","Oct-2018","Current","n","","","credit_card","Credit card refinancing","836xx","ID","15.31","0","Aug-2012","0","","97","9","1","5996","34.5%","11","w","3686.37","3686.37","2652.39","2652.39","1913.63","738.76","0.0","0.0","0.0","Dec-2019","190.21","Jan-2020","Nov-2019","0","","1","Individual","","","","0","0","5996","0","0","0","1","20","0","","0","2","3017","35","17400","1","0","0","3","750","4689","45.5","0","0","20","73","13","13","0","13","","20","","0","3","5","4","4","1","9","10","5","9","0","0","0","0","100","25","1","0","17400","5996","8600","0","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","23000","23000","23000"," 36 months"," 15.02%","797.53","C","C3","Tax Consultant","10+ years","MORTGAGE","75000","Source Verified","Oct-2018","Charged Off","n","","","debt_consolidation","Debt consolidation","352xx","AL","20.95","1","Aug-1985","2","22","","12","0","22465","43.6%","28","w","0.00","0.00","1547.08","1547.08","1025.67","521.41","0.0","0.0","0.0","Dec-2018","797.53","","Nov-2018","0","","1","Individual","","","","0","0","259658","4","2","3","3","6","18149","86","4","6","12843","56","51500","2","2","5","11","21638","26321","44.1","0","0","12","397","4","4","6","5","22","4","22","0","4","5","7","14","3","9","19","5","12","0","0","0","7","96.4","14.3","0","0","296500","40614","47100","21000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","10000"," 36 months"," 15.02%","346.76","C","C3","security guard","5 years","MORTGAGE","38000","Not Verified","Oct-2018","Current","n","","","debt_consolidation","Debt consolidation","443xx","OH","13.16","3","Jul-1982","0","6","","11","0","5634","37.1%","16","w","6632.21","6632.21","4846.3","4846.30","3367.79","1478.51","0.0","0.0","0.0","Dec-2019","346.76","Jan-2020","Nov-2019","0","","1","Individual","","","","0","155","77424","0","1","0","0","34","200","10","1","1","1866","42","15200","2","0","0","2","7039","4537","50.1","0","0","34","434","11","11","3","11","6","17","6","0","3","5","5","6","1","8","11","5","11","0","0","0","1","73.3","40","0","0","91403","9323","9100","2000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","5000","5000","5000"," 36 months"," 13.56%","169.83","C","C1","Payoff Clerk","10+ years","MORTGAGE","35360","Not Verified","Oct-2018","Current","n","","","debt_consolidation","Debt consolidation","381xx","TN","11.3","1","Jun-2006","0","21","","9","0","2597","27.3%","15","f","3291.41","3291.41","2373.85","2373.85","1708.59","665.26","0.0","0.0","0.0","Dec-2019","169.83","Jan-2020","Nov-2019","0","","1","Individual","","","","0","1413","69785","0","2","0","1","16","2379","40","3","4","1826","32","9500","0","0","1","5","8723","1174","60.9","0","0","147","85","9","9","2","10","21","9","21","0","1","3","2","2","6","6","7","3","9","0","0","0","3","92.9","50","0","0","93908","4976","3000","6028","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","9750"," 36 months"," 11.06%","327.68","B","B3","","n/a","RENT","44400","Source Verified","Oct-2018","Current","n","","","credit_card","Credit card refinancing","980xx","WA","11.78","0","Oct-2008","2","40","","15","0","6269","13.1%","25","f","6497.81","6335.37","4572.16","4457.86","3502.19","1069.97","0.0","0.0","0.0","Dec-2019","327.68","Jan-2020","Nov-2019","0","53","1","Individual","","","","0","520","16440","3","1","1","1","2","10171","100","2","5","404","28","47700","0","3","5","6","1265","20037","2.3","0","0","61","119","1","1","0","1","","1","40","1","2","4","6","8","3","14","22","4","15","0","0","0","3","92","0","0","0","57871","16440","20500","10171","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","10000"," 36 months"," 16.91%","356.08","C","C5","Key Accounts Manager","2 years","RENT","80000","Not Verified","Oct-2018","Current","n","","","other","Other","021xx","MA","17.72","1","Sep-2006","0","14","","17","0","1942","30.8%","31","w","6695.63","6695.63","4975.73","4975.73","3304.37","1671.36","0.0","0.0","0.0","Dec-2019","356.08","Jan-2020","Nov-2019","0","25","1","Individual","","","","0","0","59194","0","15","1","1","12","57252","85","0","0","1942","80","6300","0","5","0","1","3482","2058","48.5","0","0","144","142","40","12","0","131","30","","30","3","1","1","1","5","22","2","9","1","17","0","0","0","1","74.2","0","0","0","73669","59194","4000","67369","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""


Total amount funded in policy code 1: 2050652925
Total amount funded in policy code 2: 820081797

In [0]:
df = pd.read_csv('LoanStats_2018Q4.csv')
print(df.shape)
df.head()

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0,1,2,3,4,7,13,18,19,24,25,27,28,29,30,31,32,34,36,37,38,39,40,41,42,43,44,46,49,50,51,53,54,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,113,114,115,116,117,118,119,120,121,126,127,131,132,134,135,136,141,142,143) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

(128400, 1)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Notes offered by Prospectus (https://www.lendingclub.com/info/prospectus.action)
id  member_id loan_amnt funded_amnt funded_amnt_inv term       int_rate installment grade sub_grade emp_title           emp_length home_ownership annual_inc verification_status issue_d  loan_status pymnt_plan url desc purpose            title                   zip_code addr_state dti   delinq_2yrs earliest_cr_line inq_last_6mths mths_since_last_delinq mths_since_last_record open_acc pub_rec revol_bal revol_util total_acc initial_list_status out_prncp out_prncp_inv total_pymnt     total_pymnt_inv total_rec_prncp total_rec_int total_rec_late_fee recoveries collection_recovery_fee last_pymnt_d last_pymnt_amnt next_pymnt_d last_credit_pull_d collections_12_mths_ex_med mths_since_last_major_derog policy_code application_type annual_inc_joint dti_joint verification_status_joint acc_now_delinq tot_coll_amt tot_cur_bal open_acc_6m open_act_il open_il_12m open_il_24m mths_since_rcnt_il total_bal_il il_util open_rv_12m open_rv_24m max_bal_bc all_util total_rev_hi_lim inq_fi total_cu_tl inq_last_12m acc_open_past_24mths avg_cur_bal bc_open_to_buy bc_util chargeoff_within_12_mths delinq_amnt mo_sin_old_il_acct mo_sin_old_rev_tl_op mo_sin_rcnt_rev_tl_op mo_sin_rcnt_tl mort_acc mths_since_recent_bc mths_since_recent_bc_dlq mths_since_recent_inq mths_since_recent_revol_delinq num_accts_ever_120_pd num_actv_bc_tl num_actv_rev_tl num_bc_sats num_bc_tl num_il_tl num_op_rev_tl num_rev_accts num_rev_tl_bal_gt_0 num_sats num_tl_120dpd_2m num_tl_30dpd num_tl_90g_dpd_24m num_tl_op_past_12m pct_tl_nvr_dlq percent_bc_gt_75 pub_rec_bankruptcies tax_liens tot_hi_cred_lim total_bal_ex_mort total_bc_limit total_il_high_credit_limit revol_bal_joint sec_app_earliest_cr_line sec_app_inq_last_6mths sec_app_mort_acc sec_app_open_acc sec_app_revol_util sec_app_open_act_il sec_app_num_rev_accts sec_app_chargeoff_within_12_mths sec_app_collections_12_mths_ex_med sec_app_mths_since_last_major_derog hardship_flag hardship_type hardship_reason hardship_status deferral_term hardship_amount hardship_start_date hardship_end_date payment_plan_start_date hardship_length hardship_dpd hardship_loan_status orig_projected_additional_accrued_interest hardship_payoff_balance_amount hardship_last_payment_amount debt_settlement_flag debt_settlement_flag_date settlement_status settlement_date settlement_amount settlement_percentage                                    settlement_term
NaN NaN       6000      6000        6000             36 months  14.47%  206.44      C     C2        Manager             10+ years  RENT           55000      Verified            Dec-2018 Charged Off n          NaN NaN  credit_card        Credit card refinancing 104xx    NY         10.65 0           Jun-2006         0              NaN                    NaN                    6        0       4196      91.2%      8         w                   0.00      0.00          1106.52         1106.52         546.14          272.38        0.0                288.0      51.84                   Apr-2019     206.44          NaN          Nov-2019           0                          NaN                         1           Individual       NaN              NaN       NaN                       0              0            12514       0           2           1           1           9                  8318         74      1           1           2807       79       4600             1      0           2            2                    2086        344            92      0                        0           33                 150                  9                     9              0        9                    NaN                      9                     NaN                            0                     3              4               3           3         3         4             5             4                   6        0                0            0                  2                  100            100              0                    0         15800           12514             4300           11200                      NaN             NaN                      NaN                    NaN              NaN              NaN                NaN                 NaN                   NaN                              NaN                                NaN                                 N             NaN           NaN             NaN             NaN           NaN             NaN                 NaN               NaN                     NaN             NaN          NaN                  NaN                                        NaN                            NaN                          Y                    Oct-2019                  ACTIVE            Oct-2019        3479              60.01                                                                 24
              24000     24000       24000            36 months  10.33%  778.14      B     B1        Maintenance Manager 10+ years  MORTGAGE       100000     Not Verified        Dec-2018 Current     n          NaN NaN  debt_consolidation Debt consolidation      606xx    IL         19.14 0           Oct-1996         3              39                     NaN                    14       0       8547      27.7%      28        w                   16807.30  16807.30      9317.02         9317.02         7192.70         2124.32       0.0                0.0        0.0                     Dec-2019     778.14          Jan-2020     Nov-2019           0                          57                          1           Individual       NaN              NaN       NaN                       0              0            273876      3           5           3           5           5                  40384        66      2           4           4368       51       30900            8      0           8            9                    19563       17353          33      0                        0           266                178                  4                     4              3        4                    39                       1                     39                             1                     5              5               6           8         15        7             9             5                   14       0                0            0                  5                  82.1           16.7             0                    0         335121          50686             25900          61514                      NaN             NaN                      NaN                    NaN              NaN              NaN                NaN                 NaN                   NaN                              NaN                                NaN                                 N             NaN           NaN             NaN             NaN           NaN             NaN                 NaN               NaN                     NaN             NaN          NaN                  NaN                                        NaN                            NaN                          N                    NaN                       NaN               NaN             NaN               NaN                                                                  NaN
              30000     30000       30000            36 months  15.02%  1040.26     C     C3        Firefighter         10+ years  RENT           90000      Verified            Dec-2018 Fully Paid  n          NaN NaN  debt_consolidation Debt consolidation      681xx    NE         22.23 0           May-2007         1              NaN                    NaN                    8        0       25754     48%        23        w                   0.00      0.00          30883.673711683 30883.67        30000.00        883.67        0.0                0.0        0.0                     Feb-2019     28382.51        NaN          Nov-2019           0                          NaN                         1           Individual       NaN              NaN       NaN                       0              0            51370       1           2           1           2           9                  25616        71      2           3           9621       57       53600            0      2           1            5                    6421        22030          47      0                        0           123                139                  3                     3              3        3                    NaN                      3                     NaN                            0                     4              6               4           5         11        6             9             6                   8        0                0            0                  3                  100            50               0                    0         89849           51370             41600          36249                      NaN             NaN                      NaN                    NaN              NaN              NaN                NaN                 NaN                   NaN                              NaN                                NaN                                 N             NaN           NaN             NaN             NaN           NaN             NaN                 NaN               NaN                     NaN             NaN          NaN                  NaN                                        NaN                            NaN                          N                    NaN                       NaN               NaN             NaN               NaN                                                                  NaN
              8000      8000        8000             36 months  12.98%  269.48      B     B5        Controller          4 years    MORTGAGE       95000      Source Verified     Dec-2018 Current     n          NaN NaN  credit_card        Credit card refinancing 480xx    MI         9.44  0           Mar-2009         2              73                     NaN                    7        0       11434     33.3%      20        w                   1707.34   1707.34       6855.63         6855.63         6292.66         562.97        0.0                0.0        0.0                     Dec-2019     269.48          Jan-2020     Dec-2019           0                          73                          1           Individual       NaN              NaN       NaN                       0              0            247933      5           1           3           4           2                  13716        98      4           5           8918       52       34300            2      0           7            10                   35419       22866          33.3    0                        0           13                 117                  6                     2              1        6                    73                       2                     73                             1                     3              3               5           15        4         5             15            3                   7        0                0            0                  8                  100            20               0                    0         271550          25150             34300          14000                      NaN             NaN                      NaN                    NaN              NaN              NaN                NaN                 NaN                   NaN                              NaN                                NaN                                 N             NaN           NaN             NaN             NaN           NaN             NaN                 NaN               NaN                     NaN             NaN          NaN                  NaN                                        NaN                            NaN                          N                    NaN                       NaN               NaN             NaN               NaN                                                                  NaN

^^^ How did we know those NaN were coming from the bottom two rows?

In [0]:
# We can fix the header problem by using the 'skiprows' or 'header' parameters

df = pd.read_csv('LoanStats_2018Q4.csv', header=1)
print(df.shape)
df.head()

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

(128399, 144)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,6000.0,6000.0,6000.0,36 months,14.47%,206.44,C,C2,Manager,10+ years,RENT,55000.0,Verified,Dec-2018,Charged Off,n,NaN,NaN,credit_card,Credit card refinancing,104xx,NY,10.65,0.0,Jun-2006,0.0,NaN,NaN,6.0,0.0,4196.0,91.2%,8.0,w,0.00,0.00,1106.520000,1106.52,546.14,272.38,0.0,288.0,51.84,Apr-2019,206.44,NaN,Nov-2019,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,12514.0,0.0,2.0,1.0,1.0,9.0,8318.0,74.0,1.0,1.0,2807.0,79.0,4600.0,1.0,0.0,2.0,2.0,2086.0,344.0,92.0,0.0,0.0,33.0,150.0,9.0,9.0,0.0,9.0,NaN,9.0,NaN,0.0,3.0,4.0,3.0,3.0,3.0,4.0,5.0,4.0,6.0,0.0,0.0,0.0,2.0,100.0,100.0,0.0,0.0,15800.0,12514.0,4300.0,11200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,Oct-2019,ACTIVE,Oct-2019,3479.0,60.01,24.0
1,NaN,NaN,24000.0,24000.0,24000.0,36 months,10.33%,778.14,B,B1,Maintenance Manager,10+ years,MORTGAGE,100000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,606xx,IL,19.14,0.0,Oct-1996,3.0,39.0,NaN,14.0,0.0,8547.0,27.7%,28.0,w,16807.30,16807.30,9317.020000,9317.02,7192.70,2124.32,0.0,0.0,0.00,Dec-2019,778.14,Jan-2020,Nov-2019,0.0,57.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,273876.0,3.0,5.0,3.0,5.0,5.0,40384.0,66.0,2.0,4.0,4368.0,51.0,30900.0,8.0,0.0,8.0,9.0,19563.0,17353.0,33.0,0.0,0.0,266.0,178.0,4.0,4.0,3.0,4.0,39.0,1.0,39.0,1.0,5.0,5.0,6.0,8.0,15.0,7.0,9.0,5.0,14.0,0.0,0.0,0.0,5.0,82.1,16.7,0.0,0.0,335121.0,50686.0,25900.0,61514.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,30000.0,30000.0,30000.0,36 months,15.02%,1040.26,C,C3,Firefighter,10+ years,RENT,90000.0,Verified,Dec-2018,Fully Paid,n,NaN,NaN,debt_consolidation,Debt consolidation,681xx,NE,22.23,0.0,May-2007,1.0,NaN,NaN,8.0,0.0,25754.0,48%,23.0,w,0.00,0.00,30883.673712,30883.67,30000.00,883.67,0.0,0.0,0.00,Feb-2019,28382.51,NaN,Nov-2019,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,51370.0,1.0,2.0,1.0,2.0,9.0,25616.0,71.0,2.0,3.0,9621.0,57.0,53600.0,0.0,2.0,1.0,5.0,6421.0,22030.0,47.0,0.0,0.0,123.0,139.0,3.0,3.0,3.0,3.0,NaN,3.0,NaN,0.0,4.0,6.0,4.0,5.0,11.0,6.0,9.0,6.0,8.0,0.0,0.0,0.0,3.0,100.0,50.0,0.0,0.0,89849.0,51370.0,41600.0,36249.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,8000.0,8000.0,8000.0,36 months,12.98%,269.48,B,B5,Controller,4 years,MORTGAGE,95000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,480xx,MI,9.44,0.0,Mar-2009,2.0,73.0,NaN,7.0,0.0,11434.0,33.3%,20.0,w,1707.34,1707.34,6855.630000,6855.63,6292.66,562.97,0.0,0.0,0.00,Dec-2019,269.48,Jan-2020,Dec-2019,0.0,73.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,247933.0,5.0,1.0,3.0,4.0,2.0,13716.0,98.0,4.0,5.0,8918.0,52.0,34300.0,2.0,0.0,7.0,10.0,35419.0,22866.0,33.3,0.0,0.0,13.0,117.0,6.0,2.0,1.0,6.0,73.0,2.0,73.0,1.0,3.0,3.0,5.0,15.0,4.0,5.0,15.0,3.0,7.0,0.0,0.0,0.0,8.0,100.0,20.0,0.0,0.0,271550.0,25150.0,34300.0,14000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,22400.0,22400.0,22400.0,60 months,16.14%,546.40,C,C4,Paramedic/ Fire Fighter,10+ years,OWN,56000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,234xx,VA,18.47,0.0,Dec-2004,0.0,75.0,NaN,15.0,0.0,13555.0,38.2%,22.0,w,19230.91,19230.91,6526.670000,6526.67,3169.09,3357.58,0.0,0.0,0.00,Dec-2019,546.40,Jan-2020,Nov-2019,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,217072.0,0.0,3.0,1.0,1.0,7.0,18515.0,79.0,1.0,1.0,5789.0,55.0,35500.0,1.0,0.0,4.0,2.0,14471.0,15054.0,46.6,0.0,0.0,113.0,168.0,7.0,7.0,5.0,36.0,NaN,5.0,NaN,0.0,5.0,7.0,8.0,8.0,5.0,11.0,12.0,7.0,15.0,0.0,0.0,0.0,2.0,95.5,25.0,0.0,0.0,253539.0,32070.0,28200.0,23364.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN

^^^ How did the shape change from (128400, 1) to (128399, 144) by changing the header

---

In [0]:
df = pd.read_csv('LoanStats_2018Q4.csv', header=1 )

print(df.shape)
df.head()

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

(128399, 144)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,6000.0,6000.0,6000.0,36 months,14.47%,206.44,C,C2,Manager,10+ years,RENT,55000.0,Verified,Dec-2018,Charged Off,n,NaN,NaN,credit_card,Credit card refinancing,104xx,NY,10.65,0.0,Jun-2006,0.0,NaN,NaN,6.0,0.0,4196.0,91.2%,8.0,w,0.00,0.00,1106.520000,1106.52,546.14,272.38,0.0,288.0,51.84,Apr-2019,206.44,NaN,Nov-2019,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,12514.0,0.0,2.0,1.0,1.0,9.0,8318.0,74.0,1.0,1.0,2807.0,79.0,4600.0,1.0,0.0,2.0,2.0,2086.0,344.0,92.0,0.0,0.0,33.0,150.0,9.0,9.0,0.0,9.0,NaN,9.0,NaN,0.0,3.0,4.0,3.0,3.0,3.0,4.0,5.0,4.0,6.0,0.0,0.0,0.0,2.0,100.0,100.0,0.0,0.0,15800.0,12514.0,4300.0,11200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,Oct-2019,ACTIVE,Oct-2019,3479.0,60.01,24.0
1,NaN,NaN,24000.0,24000.0,24000.0,36 months,10.33%,778.14,B,B1,Maintenance Manager,10+ years,MORTGAGE,100000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,606xx,IL,19.14,0.0,Oct-1996,3.0,39.0,NaN,14.0,0.0,8547.0,27.7%,28.0,w,16807.30,16807.30,9317.020000,9317.02,7192.70,2124.32,0.0,0.0,0.00,Dec-2019,778.14,Jan-2020,Nov-2019,0.0,57.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,273876.0,3.0,5.0,3.0,5.0,5.0,40384.0,66.0,2.0,4.0,4368.0,51.0,30900.0,8.0,0.0,8.0,9.0,19563.0,17353.0,33.0,0.0,0.0,266.0,178.0,4.0,4.0,3.0,4.0,39.0,1.0,39.0,1.0,5.0,5.0,6.0,8.0,15.0,7.0,9.0,5.0,14.0,0.0,0.0,0.0,5.0,82.1,16.7,0.0,0.0,335121.0,50686.0,25900.0,61514.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,30000.0,30000.0,30000.0,36 months,15.02%,1040.26,C,C3,Firefighter,10+ years,RENT,90000.0,Verified,Dec-2018,Fully Paid,n,NaN,NaN,debt_consolidation,Debt consolidation,681xx,NE,22.23,0.0,May-2007,1.0,NaN,NaN,8.0,0.0,25754.0,48%,23.0,w,0.00,0.00,30883.673712,30883.67,30000.00,883.67,0.0,0.0,0.00,Feb-2019,28382.51,NaN,Nov-2019,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,51370.0,1.0,2.0,1.0,2.0,9.0,25616.0,71.0,2.0,3.0,9621.0,57.0,53600.0,0.0,2.0,1.0,5.0,6421.0,22030.0,47.0,0.0,0.0,123.0,139.0,3.0,3.0,3.0,3.0,NaN,3.0,NaN,0.0,4.0,6.0,4.0,5.0,11.0,6.0,9.0,6.0,8.0,0.0,0.0,0.0,3.0,100.0,50.0,0.0,0.0,89849.0,51370.0,41600.0,36249.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,8000.0,8000.0,8000.0,36 months,12.98%,269.48,B,B5,Controller,4 years,MORTGAGE,95000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,480xx,MI,9.44,0.0,Mar-2009,2.0,73.0,NaN,7.0,0.0,11434.0,33.3%,20.0,w,1707.34,1707.34,6855.630000,6855.63,6292.66,562.97,0.0,0.0,0.00,Dec-2019,269.48,Jan-2020,Dec-2019,0.0,73.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,247933.0,5.0,1.0,3.0,4.0,2.0,13716.0,98.0,4.0,5.0,8918.0,52.0,34300.0,2.0,0.0,7.0,10.0,35419.0,22866.0,33.3,0.0,0.0,13.0,117.0,6.0,2.0,1.0,6.0,73.0,2.0,73.0,1.0,3.0,3.0,5.0,15.0,4.0,5.0,15.0,3.0,7.0,0.0,0.0,0.0,8.0,100.0,20.0,0.0,0.0,271550.0,25150.0,34300.0,14000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,22400.0,22400.0,22400.0,60 months,16.14%,546.40,C,C4,Paramedic/ Fire Fighter,10+ years,OWN,56000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,234xx,VA,18.47,0.0,Dec-2004,0.0,75.0,NaN,15.0,0.0,13555.0,38.2%,22.0,w,19230.91,19230.91,6526.670000,6526.67,3169.09,3357.58,0.0,0.0,0.00,Dec-2019,546.40,Jan-2020,Nov-2019,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,217072.0,0.0,3.0,1.0,1.0,7.0,18515.0,79.0,1.0,1.0,5789.0,55.0,35500.0,1.0,0.0,4.0,2.0,14471.0,15054.0,46.6,0.0,0.0,113.0,168.0,7.0,7.0,5.0,36.0,NaN,5.0,NaN,0.0,5.0,7.0,8.0,8.0,5.0,11.0,12.0,7.0,15.0,0.0,0.0,0.0,2.0,95.5,25.0,0.0,0.0,253539.0,32070.0,28200.0,23364.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN

In [0]:

df = pd.read_csv('LoanStats_2018Q4.csv', header=1, skipfooter=2, engine='python')
print(df.shape)
df.head()

(128397, 144)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,6000,6000,6000.0,36 months,14.47%,206.44,C,C2,Manager,10+ years,RENT,55000.0,Verified,Dec-2018,Charged Off,n,NaN,NaN,credit_card,Credit card refinancing,104xx,NY,10.65,0,Jun-2006,0,NaN,NaN,6,0,4196,91.2%,8,w,0.00,0.00,1106.520000,1106.52,546.14,272.38,0.0,288.0,51.84,Apr-2019,206.44,NaN,Nov-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,12514,0,2,1,1,9.0,8318,74.0,1,1,2807,79.0,4600,1,0,2,2,2086.0,344.0,92.0,0,0,33.0,150,9,9,0,9.0,NaN,9.0,NaN,0,3,4,3,3,3,4,5,4,6,0.0,0,0,2,100.0,100.0,0,0,15800,12514,4300,11200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,Oct-2019,ACTIVE,Oct-2019,3479.0,60.01,24.0
1,NaN,NaN,24000,24000,24000.0,36 months,10.33%,778.14,B,B1,Maintenance Manager,10+ years,MORTGAGE,100000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,606xx,IL,19.14,0,Oct-1996,3,39.0,NaN,14,0,8547,27.7%,28,w,16807.30,16807.30,9317.020000,9317.02,7192.70,2124.32,0.0,0.0,0.00,Dec-2019,778.14,Jan-2020,Nov-2019,0,57.0,1,Individual,NaN,NaN,NaN,0,0,273876,3,5,3,5,5.0,40384,66.0,2,4,4368,51.0,30900,8,0,8,9,19563.0,17353.0,33.0,0,0,266.0,178,4,4,3,4.0,39.0,1.0,39.0,1,5,5,6,8,15,7,9,5,14,0.0,0,0,5,82.1,16.7,0,0,335121,50686,25900,61514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,30000,30000,30000.0,36 months,15.02%,1040.26,C,C3,Firefighter,10+ years,RENT,90000.0,Verified,Dec-2018,Fully Paid,n,NaN,NaN,debt_consolidation,Debt consolidation,681xx,NE,22.23,0,May-2007,1,NaN,NaN,8,0,25754,48%,23,w,0.00,0.00,30883.673712,30883.67,30000.00,883.67,0.0,0.0,0.00,Feb-2019,28382.51,NaN,Nov-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,51370,1,2,1,2,9.0,25616,71.0,2,3,9621,57.0,53600,0,2,1,5,6421.0,22030.0,47.0,0,0,123.0,139,3,3,3,3.0,NaN,3.0,NaN,0,4,6,4,5,11,6,9,6,8,0.0,0,0,3,100.0,50.0,0,0,89849,51370,41600,36249,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,8000,8000,8000.0,36 months,12.98%,269.48,B,B5,Controller,4 years,MORTGAGE,95000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,480xx,MI,9.44,0,Mar-2009,2,73.0,NaN,7,0,11434,33.3%,20,w,1707.34,1707.34,6855.630000,6855.63,6292.66,562.97,0.0,0.0,0.00,Dec-2019,269.48,Jan-2020,Dec-2019,0,73.0,1,Individual,NaN,NaN,NaN,0,0,247933,5,1,3,4,2.0,13716,98.0,4,5,8918,52.0,34300,2,0,7,10,35419.0,22866.0,33.3,0,0,13.0,117,6,2,1,6.0,73.0,2.0,73.0,1,3,3,5,15,4,5,15,3,7,0.0,0,0,8,100.0,20.0,0,0,271550,25150,34300,14000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,22400,22400,22400.0,60 months,16.14%,546.40,C,C4,Paramedic/ Fire Fighter,10+ years,OWN,56000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,234xx,VA,18.47,0,Dec-2004,0,75.0,NaN,15,0,13555,38.2%,22,w,19230.91,19230.91,6526.670000,6526.67,3169.09,3357.58,0.0,0.0,0.00,Dec-2019,546.40,Jan-2020,Nov-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,217072,0,3,1,1,7.0,18515,79.0,1,1,5789,55.0,35500,1,0,4,2,14471.0,15054.0,46.6,0,0,113.0,168,7,7,5,36.0,NaN,5.0,NaN,0,5,7,8,8,5,11,12,7,15,0.0,0,0,2,95.5,25.0,0,0,253539,32070,28200,23364,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN

In [0]:
df.tail()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
128392,NaN,NaN,23000,23000,23000.0,36 months,15.02%,797.53,C,C3,Tax Consultant,10+ years,MORTGAGE,75000.0,Source Verified,Oct-2018,Charged Off,n,NaN,NaN,debt_consolidation,Debt consolidation,352xx,AL,20.95,1,Aug-1985,2,22.0,NaN,12,0,22465,43.6%,28,w,0.00,0.00,1547.08,1547.08,1025.67,521.41,0.0,0.0,0.0,Dec-2018,797.53,NaN,Nov-2018,0,NaN,1,Individual,NaN,NaN,NaN,0,0,259658,4,2,3,3,6.0,18149,86.0,4,6,12843,56.0,51500,2,2,5,11,21638.0,26321.0,44.1,0,0,12.0,397,4,4,6,5.0,22.0,4.0,22.0,0,4,5,7,14,3,9,19,5,12,0.0,0,0,7,96.4,14.3,0,0,296500,40614,47100,21000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
128393,NaN,NaN,10000,10000,10000.0,36 months,15.02%,346.76,C,C3,security guard,5 years,MORTGAGE,38000.0,Not Verified,Oct-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,443xx,OH,13.16,3,Jul-1982,0,6.0,NaN,11,0,5634,37.1%,16,w,6632.21,6632.21,4846.30,4846.30,3367.79,1478.51,0.0,0.0,0.0,Dec-2019,346.76,Jan-2020,Nov-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,155,77424,0,1,0,0,34.0,200,10.0,1,1,1866,42.0,15200,2,0,0,2,7039.0,4537.0,50.1,0,0,34.0,434,11,11,3,11.0,6.0,17.0,6.0,0,3,5,5,6,1,8,11,5,11,0.0,0,0,1,73.3,40.0,0,0,91403,9323,9100,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
128394,NaN,NaN,5000,5000,5000.0,36 months,13.56%,169.83,C,C1,Payoff Clerk,10+ years,MORTGAGE,35360.0,Not Verified,Oct-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,381xx,TN,11.30,1,Jun-2006,0,21.0,NaN,9,0,2597,27.3%,15,f,3291.41,3291.41,2373.85,2373.85,1708.59,665.26,0.0,0.0,0.0,Dec-2019,169.83,Jan-2020,Nov-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,1413,69785,0,2,0,1,16.0,2379,40.0,3,4,1826,32.0,9500,0,0,1,5,8723.0,1174.0,60.9,0,0,147.0,85,9,9,2,10.0,21.0,9.0,21.0,0,1,3,2,2,6,6,7,3,9,0.0,0,0,3,92.9,50.0,0,0,93908,4976,3000,6028,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
128395,NaN,NaN,10000,10000,9750.0,36 months,11.06%,327.68,B,B3,NaN,NaN,RENT,44400.0,Source Verified,Oct-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,980xx,WA,11.78,0,Oct-2008,2,40.0,NaN,15,0,6269,13.1%,25,f,6497.81,6335.37,4572.16,4457.86,3502.19,1069.97,0.0,0.0,0.0,Dec-2019,327.68,Jan-2020,Nov-2019,0,53.0,1,Individual,NaN,NaN,NaN,0,520,16440,3,1,1,1,2.0,10171,100.0,2,5,404,28.0,47700,0,3,5,6,1265.0,20037.0,2.3,0,0,61.0,119,1,1,0,1.0,NaN,1.0,40.0,1,2,4,6,8,3,14,22,4,15,0.0,0,0,3,92.0,0.0,0,0,57871,16440,20500,10171,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
128396,NaN,NaN,10000,10000,10000.0,36 months,16.91%,356.08,C,C5,Key Accounts Manager,2 years,RENT,80000.0,Not Verified,Oct-2018,Current,n,NaN,NaN,other,Other,021xx,MA,17.72,1,Sep-2006,0,14.0,NaN,17,0,1942,30.8%,31,w,6695.63,6695.63,4975.73,4975.73,3304.37,1671.36,0.0,0.0,0.0,Dec-2019,356.08,Jan-2020,Nov-2019,0,25.0,1,Individual,NaN,NaN,NaN,0,0,59194,0,15,1,1,12.0,57252,85.0,0,0,1942,80.0,6300,0,5,0,1,3482.0,2058.0,48.5,0,0,144.0,142,40,12,0,131.0,30.0,NaN,30.0,3,1,1,1,5,22,2,9,1,17,0.0,0,0,1,74.2,0.0,0,0,73669,59194,4000,67369,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN

In [0]:
# Sum null values by column and sort from least to greatest
pd.set_option('display.max_rows', 200)

df.isnull().sum().sort_values()

inq_fi                                             0
delinq_amnt                                        0
chargeoff_within_12_mths                           0
acc_open_past_24mths                               0
inq_last_12m                                       0
total_cu_tl                                        0
total_rev_hi_lim                                   0
max_bal_bc                                         0
open_rv_24m                                        0
open_rv_12m                                        0
total_bal_il                                       0
open_il_24m                                        0
hardship_flag                                      0
open_act_il                                        0
open_acc_6m                                        0
tot_cur_bal                                        0
tot_coll_amt                                       0
acc_now_delinq                                     0
application_type                                   0
policy_code                                        0
mo_sin_old_rev_tl_op                               0
mo_sin_rcnt_rev_tl_op                              0
mo_sin_rcnt_tl                                     0
mort_acc                                           0
total_il_high_credit_limit                         0
total_bc_limit                                     0
total_bal_ex_mort                                  0
tot_hi_cred_lim                                    0
tax_liens                                          0
pub_rec_bankruptcies                               0
pct_tl_nvr_dlq                                     0
num_tl_op_past_12m                                 0
num_tl_90g_dpd_24m                                 0
collections_12_mths_ex_med                         0
num_tl_30dpd                                       0
num_rev_tl_bal_gt_0                                0
num_rev_accts                                      0
num_op_rev_tl                                      0
num_il_tl                                          0
num_bc_tl                                          0
num_bc_sats                                        0
num_actv_rev_tl                                    0
num_actv_bc_tl                                     0
num_accts_ever_120_pd                              0
num_sats                                           0
last_pymnt_amnt                                    0
open_il_12m                                        0
debt_settlement_flag                               0
pub_rec                                            0
open_acc                                           0
grade                                              0
sub_grade                                          0
home_ownership                                     0
inq_last_6mths                                     0
annual_inc                                         0
verification_status                                0
earliest_cr_line                                   0
delinq_2yrs                                        0
issue_d                                            0
addr_state                                         0
zip_code                                           0
title                                              0
loan_status                                        0
pymnt_plan                                         0
installment                                        0
revol_bal                                          0
term                                               0
collection_recovery_fee                            0
loan_amnt                                          0
recoveries                                         0
total_rec_late_fee                                 0
funded_amnt                                        0
funded_amnt_inv                                    0
total_acc                                          0
total_rec_int                                      0
purpose                                            0
total_rec_prncp                                    0
total_pymnt_inv                                    0
total_pymnt                                        0
out_prncp_inv                                      0
out_prncp                                          0
initial_list_status                                0
int_rate                                           0
last_credit_pull_d                                 1
avg_cur_bal                                       13
all_util                                          37
revol_util                                       156
last_pymnt_d                                     159
dti                                              237
mths_since_recent_bc                            1591
bc_open_to_buy                                  1691
percent_bc_gt_75                                1692
bc_util                                         1754
num_tl_120dpd_2m                                2859
mths_since_rcnt_il                              4478
mo_sin_old_il_acct                              4478
emp_length                                     11701
mths_since_recent_inq                          16047
il_util                                        20274
emp_title                                      20942
next_pymnt_d                                   26736
mths_since_last_delinq                         72190
mths_since_recent_revol_delinq                 91620
mths_since_last_major_derog                    99223
mths_since_recent_bc_dlq                      103232
sec_app_open_acc                              111619
sec_app_mort_acc                              111619
sec_app_inq_last_6mths                        111619
sec_app_earliest_cr_line                      111619
revol_bal_joint                               111619
sec_app_open_act_il                           111619
annual_inc_joint                              111619
dti_joint                                     111619
sec_app_collections_12_mths_ex_med            111619
sec_app_chargeoff_within_12_mths              111619
sec_app_num_rev_accts                         111619
sec_app_revol_util                            111877
mths_since_last_record                        112950
verification_status_joint                     113553
sec_app_mths_since_last_major_derog           123245
debt_settlement_flag_date                     127946
settlement_date                               127946
settlement_amount                             127946
settlement_status                             127946
settlement_term                               127946
settlement_percentage                         127946
hardship_status                               128164
deferral_term                                 128164
hardship_amount                               128164
hardship_start_date                           128164
hardship_end_date                             128164
payment_plan_start_date                       128164
hardship_length                               128164
hardship_dpd                                  128164
hardship_loan_status                          128164
hardship_reason                               128164
hardship_payoff_balance_amount                128164
hardship_last_payment_amount                  128164
hardship_type                                 128164
orig_projected_additional_accrued_interest    128191
url                                           128397
member_id                                     128397
desc                                          128397
id                                            128397
dtype: int64

In [0]:
# dropping the empty columns 

df.shape

# df = df.drop(['url', 'member_id', 'desc', 'id'], axis=1)

# df.head()

(128397, 144)

In [0]:
### Look at the first 10 values of the int_rate column
df['int_rate'][:10]

0     14.47%
1     10.33%
2     15.02%
3     12.98%
4     16.14%
5     12.98%
6     15.02%
7     16.14%
8     14.47%
9     13.56%
Name: int_rate, dtype: object

In [0]:
### Look at a specific value from the int_rate column

int_rate = df['int_rate'][2]

int_rate

' 15.02%'

In [0]:
"""
Problems that we need to address with this column:

String column that should be numeric
Percent Sign % included with the number
Leading space at the beginning of the string

"""


print(int_rate.strip().strip('%'))

type(int_rate.strip().strip('%'))

15.02

str

In [0]:
### "Cast" the string value to a float

float(int_rate.strip().strip('%'))

15.02

In [0]:
type(float(int_rate.strip().strip('%')))

float

In [0]:
### Write a function that can do what we have written above to any 
### string that is passsed to it.
term_rate = df['term'][2]


def str_to_int(cell_contents):
  return int(cell_contents.strip().strip(' months'))

str_to_int(term_rate)

36

In [0]:
### is the data type correct?

type(str_to_int(term_rate))

int

In [84]:
# .apply()to every cell in term column from str to int

df['term_integer'] = df['term_rate'].apply(str_to_int)

df.head()

KeyError: ignored

In [91]:
# Make a column named 'loan_status_is_great'. It should contain the integer 1 
# if 'loan_status' is "Current" or "Fully Paid." Else it should contain the integer 0.

df['loan_status_is_great'] = df[df['loan_status'] == "Current" or df['loan_status'] == "Fully Paid"]


def str_to_int(loan_status):
  return 1 if loan_status is True else 0

df['loan_status_is_great'] = df['loan_status_is_great'].apply(str_to_int)

ValueError: ignored

In [95]:
# Make last_pymnt_d_month and last_pymnt_d_year columns.

import pandas as pd

[col for col in df if col.endswith('_d')]

df['last_pymnt_d'] = pd.to_datetime(df['last_pymnt_d'], infer_datetime_format=True)

df['last_pymnt_d'].head().values

array(['2019-04-01T00:00:00.000000000', '2019-12-01T00:00:00.000000000',
       '2019-02-01T00:00:00.000000000', '2019-12-01T00:00:00.000000000',
       '2019-12-01T00:00:00.000000000'], dtype='datetime64[ns]')

In [96]:
df['last_pymnt_d_month'] = df['last_pymnt_d'].dt.month

df['last_pymnt_d_month']

0          4.0
1         12.0
2          2.0
3         12.0
4         12.0
          ...
128392    12.0
128393    12.0
128394    12.0
128395    12.0
128396    12.0
Name: last_pymnt_d_month, Length: 128397, dtype: float64

In [97]:
df['last_pymnt_d_year'] = df['last_pymnt_d'].dt.year

df['last_pymnt_d_year']

0         2019.0
1         2019.0
2         2019.0
3         2019.0
4         2019.0
           ...
128392    2018.0
128393    2019.0
128394    2019.0
128395    2019.0
128396    2019.0
Name: last_pymnt_d_year, Length: 128397, dtype: float64

# Stretch Goals

You can do more with the LendingClub or Instacart datasets.

LendingClub options:
- There's one other column in the dataframe with percent signs. Remove them and convert to floats. You'll need to handle missing values.
- Modify the `emp_title` column to replace titles with 'Other' if the title is not in the top 20. 
- Take initiatve and work on your own ideas!

Instacart options:
- Read [Instacart Market Basket Analysis, Winner's Interview: 2nd place, Kazuki Onodera](http://blog.kaggle.com/2017/09/21/instacart-market-basket-analysis-winners-interview-2nd-place-kazuki-onodera/), especially the **Feature Engineering** section. (Can you choose one feature from his bulleted lists, and try to engineer it with pandas code?)
- Read and replicate parts of [Simple Exploration Notebook - Instacart](https://www.kaggle.com/sudalairajkumar/simple-exploration-notebook-instacart). (It's the Python Notebook with the most upvotes for this Kaggle competition.)
- Take initiative and work on your own ideas!

You can uncomment and run the cells below to re-download and extract the Instacart data

In [0]:
# !wget https://s3.amazonaws.com/instacart-datasets/instacart_online_grocery_shopping_2017_05_01.tar.gz

In [0]:
# !tar --gunzip --extract --verbose --file=instacart_online_grocery_shopping_2017_05_01.tar.gz

In [0]:
# %cd instacart_2017_05_01